### ISSUE TITLE
Update data: Tom Ward

### ISSUE THREAD

**Issue by madwort** [coreymwamba/uk-jazz-rhizome#10]
Name: Tom Ward
Instruments: Alto Saxophone, Tenor Saxophone, Baritone Saxophone, Bass Clarinet, Flute (*)
Decade music activity started (e.g. *1990* or *1930*): *2000*
Decade music activity ended (e.g. *1990* or *N/A*): *N/A*

Also, I am now a former member of Beats & Pieces Big Band. 

(*) not sure what you're expecting here, could also be "Saxophone, Bass Clarinet, Flute"?

**Comment by coreymwamba** [comment]
Done!
