### ISSUE TITLE
Click on a node to highlight?

### ISSUE THREAD

**Issue by madwort** [coreymwamba/uk-jazz-rhizome#5]
Current behaviour is:
- use the search facility to find a node (musician or group) to highlight. 
- clicking on a node allows you to drag it around

We could do:
- click on a node to highlight that node (and its connections)

What do you think? Might make it easier to traverse the graph?

**Comment by coreymwamba** [comment]
I think that's exactly what should happen! Although I am more of a
typing person, other people would love that...

On Tue, 13 Mar 2018 15:49:30 +0000 (UTC)
Tom Ward <notifications@github.com> wrote:

> Current behaviour is:
> - use the search facility to find a node (musician or group) to
> highlight. 
> - clicking on a node allows you to drag it around
> 
> We could do:
> - click on a node to highlight that node (and its connections)
> 
> What do you think? Might make it easier to traverse the graph?
> 
> 
> 



-- 
Corey Mwamba

musician, researcher, arts programmer, arts advocacy

http://www. coreymwamba.co.uk
