### ISSUE TITLE
3d visualisation

### ISSUE THREAD

**Issue by madwort** [coreymwamba/uk-jazz-rhizome#9]
We should be able to use this to make the graph a bit more wieldy:

https://github.com/vasturiano/3d-force-graph/

**Comment by coreymwamba** [comment]
That's it. So -- third dimension -- we need to decide/set this. If it's for *everyone* in the graph then we will need to collect more data... groups have time-based data (year formed/ended)...

**Comment by madwort** [comment]
Ah, I had assumed the third dimension would not be meaningful, it would just give more "space" for the graph to spread out and make it easier to navigate. It could be meaningful, though... hmmm...

**Comment by coreymwamba** [comment]
Is it possible you could pull in the visualisation you did the other week? I know we don't have data, but it just looked so amazing!!

**Comment by madwort** [comment]
yes will do, let me tidy it up a bit & I'll open a PR, maybe early next week...?

**Comment by madwort** [comment]
here you go https://github.com/coreymwamba/uk-jazz-rhizome/pull/12 
the 3d visualisation lib actually just sets up everything pretty much the way we need, so verry little to do!

**Comment by coreymwamba** [comment]
Ah -- no SVG generated on implementation... I have the other libraries
(check source at the site). I wonder if I have missed a step?

**Comment by coreymwamba** [comment]
Ah -- no SVG generated on implementation... I have the other libraries (check source at the site). I wonder if I have missed a step?

**Comment by coreymwamba** [comment]
Wait -- I am assuming that this generates an SVG. Does it?

**Comment by coreymwamba** [comment]
It does not! I had not noticed that it is WebGL. I guess we need to work out how to get back some of the functionality (highlighting &c.) but this looks incredible. I've put it on https://www.coreymwamba.co.uk/resources/rhizome/3d.html for now, and then we can work on the other parts.

**Comment by madwort** [comment]
Ah yeah, sorry, it doesn't do any of those things - highlighting etc - yet!
